box_memory: 8192
box_cpus: 4
box_cpu_max_exec_cap: "90"
box_video_ram: 16
disksize: "60GB"
ip_address: "192.168.99.100"
host_network: ~ # If vagrant ask for a network device, you may define it's label here.
host_ip_address: "192.168.99.1"
ca_certificates:
  ca_certs_file: ~ # Path where ca-certificates.crt is stored (C:/Users/USER/ca-certificates.crt)
  ca_certs_glob: ~ # Set to a glob expression where CA certificates are stored (C:/Users/USER/.ca-certificates/{GFI_Informatique*.crt,fwca.annuaire.groupe.local.crt})
env:
  CURL_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  REQUESTS_CA_BUNDLE: /etc/ssl/certs/ca-certificates.crt
  NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
  SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
  COMPOSE_DOCKER_CLI_BUILD: 1  # Delegates builds to docker CLI
  DOCKER_BUILDKIT: 1  # Enable buildkit support for docker CLI
  AZ_USERNAME: azure-user-name
  AZ_PASSWORD: "azure-password"
  AZ_TENANT: azure-tenant
#  DOCKER_DEVBOX_CA_CERTIFICATES: /etc/ssl/certs/GFI_Informatique*.pem /etc/ssl/certs/fwca.annuaire.groupe.local.pem
#provision_options: ['vpnc', 'azure-cli', 'vsftpd', 'gfi']  # Provisionning options (To provision additional scripts from provision/options directory)
#synced_folders_plugin: ~ # "nfs4j", "winnfsd", or "vagrant". If null, it will find the best available plugin.
#box_monitor_count: 1 # Number of screen
#gui: false # Enable gui on startup
#desktop: false # Install KDE Plasma and enable gui
## Configure folders to share here
## Use this naming convention to match docker for windows and allow docker PHPStorm support
#synced_folders:
#  user:
#    source: 'C:\Users\user' # absolute or relative path from Vagrantfile
#    target: '/c/Users/user' # absolute or relative path from home of VM
#  projects:
#    source: 'D:\projects' # absolute or relative path from Vagrantfile
#    target: '/d/projects' # absolute or relative path from home of VM
#persistent_storage:
#  location: 'D:\persistent_storage.vdi'
#  size_in_gb: 100
